write:
    create-empty-file: false
logging:
    severity: TRACE
    format: ""
    file-path: ""
    log-rotate:
        max-file-size-mb: 512
        backup-file-count: 10
        compress: true
file-cache:
    max-size-mb: 0
    cache-file-for-range-read: false
    enable-crc: false
cache-dir: ""
metadata-cache: {}
list:
    enable-empty-managed-folders: false
gcs-connection: {}
gcs-auth:
    anonymous-access: false
enable-hns: true
file-system:
    ignore-interrupts: false
    disable-parallel-dirops: false
    kernel-list-cache-ttl-secs: 0
gcs-retries:
    max-retry-attempts: 0
